const data = [
  {
    id: 1,
    name: "Trung Tâm Y Khoa Việt Đức",
    address: "Nam Từ Liêm - Hà Nội",
    phoneNumber: "0987654321",
    doctorCount: 10,
  },
  {
    id: 2,
    name: "Bệnh Viện Bạch Mai",
    address: "Đống Đa - Hà Nội",
    phoneNumber: "02438693731",
    doctorCount: 25,
  },
  {
    id: 3,
    name: "Phòng Khám Đa Khoa Hoàn Mỹ",
    address: "Quận 3 - TP. Hồ Chí Minh",
    phoneNumber: "02839309999",
    doctorCount: 15,
  },
  {
    id: 4,
    name: "Trung Tâm Y Tế Quận 1",
    address: "Quận 1 - TP. Hồ Chí Minh",
    phoneNumber: "02838212345",
    doctorCount: 12,
  },
  {
    id: 5,
    name: "Bệnh Viện Trung Ương Huế",
    address: "Thừa Thiên Huế",
    phoneNumber: "02343822222",
    doctorCount: 30,
  },
  {
    id: 6,
    name: "Phòng Khám Đa Khoa An Khang",
    address: "Cầu Giấy - Hà Nội",
    phoneNumber: "02437912345",
    doctorCount: 8,
  },
  {
    id: 7,
    name: "Trung Tâm Y Khoa Hòa Hảo",
    address: "Quận 10 - TP. Hồ Chí Minh",
    phoneNumber: "02839557979",
    doctorCount: 20,
  },
  {
    id: 8,
    name: "Bệnh Viện Phụ Sản Hà Nội",
    address: "Hai Bà Trưng - Hà Nội",
    phoneNumber: "02438523252",
    doctorCount: 18,
  },
  {
    id: 9,
    name: "Bệnh Viện Chợ Rẫy",
    address: "Quận 5 - TP. Hồ Chí Minh",
    phoneNumber: "02838554137",
    doctorCount: 40,
  },
  {
    id: 10,
    name: "Phòng Khám Quốc Tế Victoria",
    address: "Quận 7 - TP. Hồ Chí Minh",
    phoneNumber: "02837712345",
    doctorCount: 10,
  },
  {
    id: 11,
    name: "Bệnh Viện E",
    address: "Cầu Giấy - Hà Nội",
    phoneNumber: "02437543650",
    doctorCount: 22,
  },
  {
    id: 12,
    name: "Trung Tâm Y Tế Quận Bình Thạnh",
    address: "Bình Thạnh - TP. Hồ Chí Minh",
    phoneNumber: "02835512345",
    doctorCount: 14,
  },
  {
    id: 13,
    name: "Bệnh Viện Nhi Trung Ương",
    address: "Đống Đa - Hà Nội",
    phoneNumber: "02462738573",
    doctorCount: 28,
  },
  {
    id: 14,
    name: "Phòng Khám Đa Khoa Medic",
    address: "Quận 10 - TP. Hồ Chí Minh",
    phoneNumber: "02839270284",
    doctorCount: 16,
  },
  {
    id: 15,
    name: "Bệnh Viện Đa Khoa Thái Bình",
    address: "Thái Bình",
    phoneNumber: "02273812345",
    doctorCount: 12,
  },
  {
    id: 16,
    name: "Bệnh Viện Ung Bướu TP.HCM",
    address: "Bình Thạnh - TP. Hồ Chí Minh",
    phoneNumber: "02838433041",
    doctorCount: 35,
  },
  {
    id: 17,
    name: "Bệnh Viện Da Liễu Hà Nội",
    address: "Hoàn Kiếm - Hà Nội",
    phoneNumber: "02438433422",
    doctorCount: 11,
  },
  {
    id: 18,
    name: "Trung Tâm Y Tế Quận 9",
    address: "TP. Thủ Đức - TP. Hồ Chí Minh",
    phoneNumber: "02837303322",
    doctorCount: 9,
  },
  {
    id: 19,
    name: "Bệnh Viện Đa Khoa Đà Nẵng",
    address: "Đà Nẵng",
    phoneNumber: "02363822345",
    doctorCount: 27,
  },
  {
    id: 20,
    name: "Phòng Khám Đa Khoa Tân Bình",
    address: "Tân Bình - TP. Hồ Chí Minh",
    phoneNumber: "02838112345",
    doctorCount: 13,
  },
];

export { data };
